//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rechnung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rechnung()
        {
            this.Rechnung_element = new HashSet<Rechnung_element>();
        }
    
        public int Rechnung_id { get; set; }
        public string Rechnung_status { get; set; }
        public System.DateTime Rechnung_datum { get; set; }
        public int Mitarbeiter_id { get; set; }
        public Nullable<int> Tisch_ID { get; set; }
    
        public virtual Mitarbeiter Mitarbeiter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rechnung_element> Rechnung_element { get; set; }
    }
}
