//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rechnung_element
    {
        public int Rechnung_element_id { get; set; }
        public Nullable<int> Rechnung_id { get; set; }
        public int Produkt_ID { get; set; }
        public int Anzahl { get; set; }
    
        public virtual Rechnung Rechnung { get; set; }
        public virtual Speise Speise { get; set; }
    }
}
